ALTER TABLE "job_cards"
  ADD COLUMN IF NOT EXISTS "labour_cost_ghs"   DECIMAL(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "machine_cost_ghs"  DECIMAL(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "overhead_cost_ghs" DECIMAL(18,4) NOT NULL DEFAULT 0;
