ALTER TABLE "purchase_orders"
  ADD COLUMN IF NOT EXISTS "freight_cost_usd"  DECIMAL(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "clearing_cost_ghs" DECIMAL(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "other_landed_ghs"  DECIMAL(18,4) NOT NULL DEFAULT 0;
